// <auto-generated />
using Digikala.Services.CouponApi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Digikala.Services.CouponApi.Migrations
{
    [DbContext(typeof(Digikalacoupon))]
    partial class DigikalacouponModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.17")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Digikala.Services.CouponApi.Models.digicoupon", b =>
                {
                    b.Property<int>("DigicouponID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Amount")
                        .HasColumnType("int");

                    b.HasKey("DigicouponID");

                    b.ToTable("digicoupons");
                });

            modelBuilder.Entity("Digikala.Services.CouponApi.Models.giftcard", b =>
                {
                    b.Property<int>("GiftcardID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Amount")
                        .HasColumnType("int");

                    b.Property<int>("GiftcartCode")
                        .HasColumnType("int");

                    b.HasKey("GiftcardID");

                    b.ToTable("giftcards");
                });
#pragma warning restore 612, 618
        }
    }
}
